### ISSUE TITLE
AttributeError: module 'xacro' has no attribute 'process'

### ISSUE THREAD

**Issue by AlexCardaillac** [Liquid-ai/Plankton#37]
Hi, I tried to follow the steps of the README.md, but when it comes to part 5. Test the package, I have this error when I try to spawn the robot:
`File "/home/alexandre/ros2_ws/install/uuv_descriptions/share/uuv_descriptions/launch/upload_rexrov_default.launch.py", line 101, in launch_setup
doc = xacro.process(xacro_file, mappings=mappings)
AttributeError: module 'xacro' has no attribute 'process'
`
I have python 3.8.10, followed all the previous steps and correctly sourced the requiered files.
Am I missing something?

**Comment by matosinho** [comment]
Same thing here...
